org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.13

minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.215
neo_version_range=[21.1.0,)
loader_version_range=[4,)

mod_id=iska_lib
mod_name=Iskandert Library
mod_license=MIT
mod_version=1.7.0.0.0
mod_group_id=net.unfamily.iskalib
mod_authors=Unfamily, Iskandert
mod_description=Shared library for Iskandert's mods: teams, stages, structures, scanner markers, gas and liquids.

